import { CodeBlock } from '../../components/CodeBlock'

export function UnderTheHood() {
  return (
    <article className="doc-article">
      <h1>Under the Hood</h1>
      <p className="doc-lead">
        What actually happens when you call <code>publish</code> or a collection
        mutation. Message envelopes, HMAC signing, sequence numbers, and how
        the library reconciles incoming events with local state.
      </p>

      <h2 id="message-envelope">The message envelope</h2>
      <p>
        Every message sent over the wire is wrapped in a standard envelope before
        it reaches the transport. You never construct this yourself &mdash; the
        library builds it automatically from whatever you pass to{' '}
        <code>publish</code> or return from <code>onInsert</code> /{' '}
        <code>onUpdate</code>.
      </p>
      <CodeBlock
        title="Wire format (JSON)"
        code={`{
  "ch":  "tasks:{projectId:proj_1}",   // serialized channel key
  "seq": 42,                            // monotonic sequence number
  "ts":  1700000000000,                 // server-assigned timestamp (ms)
  "nonce": "a1b2c3d4",                 // optimistic echo suppression (optional)
  "hmac": "sha256=3f2a…",              // HMAC-SHA256 over ch+seq+ts+payload
  "data": { /* your payload */ }
}`}
      />
      <div className="doc-grid">
        <div className="doc-grid-card">
          <h3>ch</h3>
          <p>
            The channel key serialized to a stable string via{' '}
            <code>serializeKey</code>. Parameters are sorted so{' '}
            <code>['tasks', {'{'} projectId, userId {'}'}]</code> always
            produces the same string regardless of object key order.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>seq</h3>
          <p>
            A per-channel monotonic counter maintained by the server. Clients
            use this to detect gaps (missed messages) and trigger gap recovery.
            The sequence is per-channel, not global.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>ts</h3>
          <p>
            Server-assigned Unix timestamp in milliseconds. Used as the
            Lamport clock for LWW CRDT fields &mdash; the client&rsquo;s local
            clock is never trusted for conflict resolution.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>nonce</h3>
          <p>
            Present only when <code>optimistic: true</code> is set. A random
            hex string generated by the client when it applies an optimistic
            mutation. The server echoes it back so the client can drop the
            duplicate instead of flashing the update twice.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>hmac</h3>
          <p>
            HMAC-SHA256 over <code>ch + seq + ts + JSON.stringify(data)</code>{' '}
            using a shared secret. Lets receivers verify that a message was
            produced by a trusted server and hasn&rsquo;t been tampered with
            in transit.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>data</h3>
          <p>
            Your raw payload exactly as passed to <code>publish</code> or
            returned from a mutation callback. The library does not transform
            it.
          </p>
        </div>
      </div>

      <h2 id="hmac-signing">HMAC signing</h2>
      <p>
        The server signs every outgoing message with a secret that is never
        sent to clients. This gives clients a way to verify that a message
        genuinely came from their backend and wasn&rsquo;t injected by a
        third party (e.g. a malicious relay or a man-in-the-middle on an
        unencrypted connection).
      </p>
      <CodeBlock
        title="server/realtime.ts — configuring the signing secret"
        code={`import { createNodeServer } from '@tanstack/realtime-preset-node'

export const nodeServer = createNodeServer({
  // Generate with: openssl rand -hex 32
  signingSecret: process.env.REALTIME_SIGNING_SECRET,

  getUser: (req) => verifyJwt(req.headers.authorization),
  authorize: async (userId, channel) => ({
    subscribe: true,
    publish: userId !== null, // only authenticated users may publish
    presence: true,
  }),
})`}
      />
      <p>
        On the client side, signature verification is enabled by passing the
        same secret (or a derived public key) to the transport. The client
        rejects any message whose HMAC does not match.
      </p>
      <CodeBlock
        title="app/client.ts"
        code={`import { createRealtimeClient, wsTransport } from '@tanstack/realtime'

export const realtimeClient = createRealtimeClient({
  transport: wsTransport({
    url: 'wss://rt.example.com',
    verifyHmac: true, // reject messages with invalid signatures
  }),
})`}
      />
      <div className="doc-callout">
        <p>
          HMAC verification protects <em>message integrity</em>. It does not
          replace channel authorization &mdash; a client with a valid JWT can
          still subscribe to any channel their <code>authorize</code> callback
          allows. Use authorization rules to control <em>who</em> can
          subscribe; use HMAC to ensure messages are <em>authentic</em>.
        </p>
      </div>

      <h2 id="message-augmentation">How collection mutations become messages</h2>
      <p>
        When a TanStack DB collection mutation completes (insert, update,
        delete), the library intercepts the result and augments it into a
        channel message automatically. You never call <code>publish</code>{' '}
        yourself &mdash; just return the saved row from your callback.
      </p>
      <CodeBlock
        title="What happens step by step"
        code={`// 1. UI triggers a mutation
collection.insert({ id: 'task_1', title: 'Buy milk' })

// 2. Library calls your onInsert callback
onInsert: async ({ transaction }) => {
  const row = await db.tasks.create({ data: transaction.mutations[0].modified })
  return row  // ← returning the row is the trigger
}

// 3. Library wraps the returned row in an envelope
// {
//   ch: 'tasks:{projectId:proj_1}',
//   seq: 43,
//   ts: <server clock>,
//   nonce: 'a1b2c3' (if optimistic: true),
//   hmac: '…',
//   data: { action: 'insert', row: { id: 'task_1', title: 'Buy milk' } }
// }

// 4. Envelope is published to all channel subscribers
//    (When serverPublish: true, steps 3-4 happen server-side instead)

// 5. Each subscriber's onInsert / onUpdate / onDelete is called with row

// 6. If nonce matches a pending optimistic update, the echo is suppressed`}
      />

      <h2 id="sequence-numbers">Sequence numbers and gap detection</h2>
      <p>
        Each channel maintains a monotonic <code>seq</code> counter on the
        server. Clients track the last seen sequence number for each
        subscription. On every incoming message the client checks:
      </p>
      <ul>
        <li>
          <strong>seq === last + 1</strong> — normal, apply the message.
        </li>
        <li>
          <strong>seq &gt; last + 1</strong> — gap detected. One or more
          messages were missed (network blip, reconnect). Trigger gap recovery.
        </li>
        <li>
          <strong>seq &le; last</strong> — duplicate or out-of-order. Discard
          silently.
        </li>
      </ul>
      <p>
        Gap recovery re-runs the collection&rsquo;s <code>queryFn</code> (or
        calls <code>withGapRecovery</code> at the transport level) and diffs
        the fresh server state against local state. See{' '}
        <a href="#/docs/resilience">Resilience</a> for details and channel
        recovery for long-lived sessions.
      </p>

      <h2 id="crdt-merge">How CRDT fields are merged</h2>
      <p>
        When you declare <code>fields: {'{'} votes: &apos;pn-counter&apos; {'}'}</code>,
        the library intercepts the raw payload before it reaches your
        collection and runs the field-level merge algorithm:
      </p>
      <div className="doc-grid">
        <div className="doc-grid-card">
          <h3>lww</h3>
          <p>
            Last-write-wins register. Each incoming value carries the
            server <code>ts</code>. The higher timestamp wins. Ties are broken
            by node ID to ensure all replicas converge to the same value.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>pn-counter</h3>
          <p>
            Positive/negative counter. Each client sends a signed delta, not
            an absolute value. The server accumulates deltas from all clients;
            the result is the true sum regardless of order.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>or-set</h3>
          <p>
            Observed-remove set. Each element carries a unique tag when added.
            An add always wins over a concurrent remove because the remove only
            affects a specific tag, not future re-adds.
          </p>
        </div>
        <div className="doc-grid-card">
          <h3>local</h3>
          <p>
            Client-only field. Never serialized into the envelope and never
            broadcast. Useful for UI-only state (e.g. <code>isExpanded</code>)
            that should not leak to other clients.
          </p>
        </div>
      </div>

      <h2 id="optimistic-echo">Optimistic updates and echo suppression</h2>
      <p>
        With <code>optimistic: true</code>, the collection applies the
        mutation to local state immediately, before the server round-trip
        completes. A random <code>nonce</code> is attached to the outgoing
        message. When the server echoes the message back to the publishing
        client, the client sees the nonce in its pending-nonce set, discards
        the echo, and clears the nonce. Other clients receive the message
        normally because they have no matching nonce.
      </p>
      <CodeBlock
        code={`realtimeCollectionOptions({
  // ...
  optimistic: true,
  // Called if the server rejects the mutation (e.g. validation failure)
  onOptimisticError: (error, nonce) => {
    toast.error('Change rejected: ' + error.message)
    // The optimistic row is automatically rolled back
  },
})`}
      />
    </article>
  )
}
