/* eslint-disable */

// This file is auto-generated by TanStack Router when running `vinxi dev`.
// Do not edit it — your changes will be overwritten.
// It is committed as a stub so TypeScript and static analysis tools can resolve
// the import in router.tsx without requiring a build step.

import type { FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
  }
}

const IndexRouteWithChildren = IndexRoute

export const routeTree = rootRoute._addFileChildren([IndexRouteWithChildren])

export type RouterType = typeof routeTree
